// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFivmv1IKa2yu3vyswFl98LFm_CTZN4rM',
    appId: '1:263363857833:web:cffb95b4d9f86fc96e88b8',
    messagingSenderId: '263363857833',
    projectId: 'menugenerator-90680',
    authDomain: 'menugenerator-90680.firebaseapp.com',
    storageBucket: 'menugenerator-90680.appspot.com',
    measurementId: 'G-EK0B882ENF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLNwC40t9mf-P8I3Bf-jLTlv8Q4IlL4kI',
    appId: '1:263363857833:android:b19925300e5c5bd16e88b8',
    messagingSenderId: '263363857833',
    projectId: 'menugenerator-90680',
    storageBucket: 'menugenerator-90680.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0icaCI1gtM2GwHqE17EwYo_J6y7GmrBU',
    appId: '1:263363857833:ios:8445063bb2ae68a76e88b8',
    messagingSenderId: '263363857833',
    projectId: 'menugenerator-90680',
    storageBucket: 'menugenerator-90680.appspot.com',
    iosBundleId: 'com.example.jackAndChill',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0icaCI1gtM2GwHqE17EwYo_J6y7GmrBU',
    appId: '1:263363857833:ios:8445063bb2ae68a76e88b8',
    messagingSenderId: '263363857833',
    projectId: 'menugenerator-90680',
    storageBucket: 'menugenerator-90680.appspot.com',
    iosBundleId: 'com.example.jackAndChill',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFivmv1IKa2yu3vyswFl98LFm_CTZN4rM',
    appId: '1:263363857833:web:e868b0344e476e566e88b8',
    messagingSenderId: '263363857833',
    projectId: 'menugenerator-90680',
    authDomain: 'menugenerator-90680.firebaseapp.com',
    storageBucket: 'menugenerator-90680.appspot.com',
    measurementId: 'G-T7CYMGGYNM',
  );
}
